### ISSUE TITLE
Long time for Backups rotation

### ISSUE THREAD

**Issue by achmet9948** [pedroetb/rsync-incremental-backup#14]
Hello, 

i do every night a backup for my owncloud instance. There are round about 100 GB to backup. 
The connection from my Server to the Backup Device is realized with an openvpn connection. 

The step "Backup rotations begins" need more than 20 hours. So it is not really practibal. 
Have you some ideas?

**Comment by pedroetb** [comment]
Hi. Definitely, 20 hours is way too much for backup rotation. I backup ~300GB weekly and rotation only takes about 2 minutes (running on a modest [Banana Pi](http://www.lemaker.org/product-bananapi-specification.html) with disks mounted from a NAS on the local network).

Can you give more details about the backup device and disks used? They are connected directly to it or through network? I think you may have a bottleneck in there (disks too slow or degraded, communication too slow between device and disks, device too slow or too busy with other tasks...).

**Comment by achmet9948** [comment]
Yes I think so. 
My bakup device is a Synology NAS and the disk are in there. So they are connect directly. 
My Disk are Western Digital RED. 

My server is in a data center and is via OPENVPN connected directly to my nas. 
The server have a data transfer conncetion from 130 Gbit/s. 
My Home conncetion have a download rate from 400 Mbit/s and an upload rate from 50 Mbit/s.

In the upload monitor fro my router I can see, that my private network upload with 16 Mbit/s to my server.

**Comment by pedroetb** [comment]
Ok, all seems right.

Backup rotation only moves backup directories, from 1 to 2, from 2 to 3 and so on, and delete the last one, if exists. Should not be so heavy.
Can you try another type of connection instead of vpn? Maybe ssh directly from your server to your home.

**Comment by jezek** [comment]
Sorry for intrusion...

Like @pedroetb said, the backup rotation process is just a ```mv``` command executed on your server. It's the same, as if you execute ```mv .../backup.1 .../backup.2```, so it has to be connection independent.
https://github.com/pedroetb/rsync-incremental-backup/blob/225d66251142d22ac98d21fc87499638222852d4/rsync-incremental-backup-remote#L114

Can it be, that @achmet9948 has the disks in RAID1, and when he makes the ```mv``` command, the duplication process takes place and it takes a while? Maybe something wrong with RAID1 configuration. Anyway the length of ```mv``` command on backup direcory can be tested. Example:
```
$ du -hs backup.1
7,2G	backup.1

$ time mv backup.1 backup.tmp
real	0m0.002s
user	0m0.000s
sys	0m0.001s
```
Note: Don't forget to rename ```backup.tmp``` to ```backup.1``` after test. ;)

Hope some of my thoughts are helpful.

**Comment by pedroetb** [comment]
Thanks for intrusion @jezek!

RAID1 may be related to the issue, good point.

@achmet9948 please, try jezek suggestion and report results. You can also test your backup process to another unit, connected to your NAS through USB.

Thanks!

**Comment by achmet9948** [comment]
So, I connected a USB-Disk to my Synology. Now the script hangs at "sending incremental file list". I canceled it after 1.5 hours

**Comment by pedroetb** [comment]
So strange.. I don't know the origin of your issue. Maybe some IO limitation on your remote server?

**Comment by achmet9948** [comment]
Sorry for the delay. 
I have now tested several things: 
- USB disk to Synology --> No improvement
- Virus system deactivated on Synology --> No improvement
- I/O tested: 
With cache: 
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 14.2963 s, 75.1 MB/s
Without cache: 
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 11.73 s, 91.5 MB/s

Next I will try to write a backup directly to my computer (away from Synology)

**Comment by achmet9948** [comment]
The current resource usage on my synology at the "sending incremental file list" or "building file list" step:

![image](https://user-images.githubusercontent.com/35784592/50377433-924f4e80-061d-11e9-88a8-a4c1c7f96e98.png)

![image](https://user-images.githubusercontent.com/35784592/50377440-b9a61b80-061d-11e9-9c71-f7b4f87371ef.png)

![image](https://user-images.githubusercontent.com/35784592/50377448-cc205500-061d-11e9-9138-6adc12beea9d.png)

**Comment by achmet9948** [comment]
Here the Log. 
From Building file list to start backup: 
```
[2018-12-22T19:09:08+01:00] You are going to backup
        from:  /var/www/owncloud
        to:    /mnt/nas/owncloud/data
[2018-12-22T19:09:09+01:00] Old logs sending begins
2018/12/22 19:09:09 [12397] building file list
2018/12/22 19:09:09 [12397] sent 38 bytes  received 12 bytes  100.00 bytes/sec
2018/12/22 19:09:09 [12397] total size is 0  speedup is 0.00
[2018-12-22T19:09:09+01:00] Old logs sending finished
[2018-12-22T19:09:09+01:00] Last backup failed, backups will not be rotated
[2018-12-22T19:09:09+01:00] Backup begins
2018/12/22 19:09:09 [12411] building file list
2018/12/22 21:51:42 [12411] .d..t...... data/steffen/files/Documents/
```

**Comment by achmet9948** [comment]
Wow, only 15 minutes for about 35G

[2018-12-22T23:44:52+01:00] Backups rotation begins
[2018-12-22T23:44:53+01:00] Backups rotation finished

[2018-12-22T23:44:53+01:00] Backup begins

2018/12/22 23:44:53 [1488] building file list
2018/12/22 23:44:53 [1488] created directory /mnt/nas/owncloud/data
2018/12/22 23:49:21 [1488] cd..t...... data/*
2018/12/22 23:50:59 [1488] cd..t...... data/*
2018/12/22 23:59:47 [1488] sent 173.98K bytes  received 1.70K bytes  196.40 bytes/sec
2018/12/22 23:59:47 [1488] total size is 34.90G  speedup is 198,672.95

[2018-12-22T23:59:47+01:00] Backup completed successfully

**Comment by pedroetb** [comment]
Then the problem is a (cpu? iops?) limit when searching for changes in files. Without `c` parameter, it only compares modification timestamps, so it is faster. If you don't need to check changes in deep (generating a hash with file content to compare), you should go this way.

**Comment by achmet9948** [comment]
Could be. But according to the overview the CPU usage is not too high. 
Could it still be the main memory? My Synology has only 1GB
