### ISSUE TITLE
user

### ISSUE THREAD

**Issue by privatesam** [pedroetb/rsync-incremental-backup#15]
Using the remote script if you are ssh'ing as a specific user you need to preface the 'remote' variable.

This variable:
`remote="${3:-ssh_remote}"`

I had set as:
`remote="${3:-192.168.1.53}"`

But the user that I'm running the script as on the server to be backed up was 'admin' but the user at the other end is 'kelly', so ensure the variable is set as:
`remote="${3:-kelly@192.168.1.53}"`

The error log was only spitting out remote destination was not available.  Maybe we should make a variable for user or maybe its such a specific use case its not necessary?

**Comment by jezek** [comment]
You don't have to edit the script (if not really necessary) to set ```remote``` variable.. 

The remote variable, is set from third parameter to the script.
In your case ```rsync-incremental-backup-remote /backup/from/dir/on/server /backup/to/dir/on/remote kelly@196.168.1.53```

Other varlibles can be set as shell variable, as described in Read.md's [Customizing Configuration Values](https://github.com/pedroetb/rsync-incremental-backup/blob/master/README.md#customizing-configuration-values) section.

If you really want to edit the ```remote``` variable in script, change the line
```remote="${3:-ssh_remote}"```

directly to:
remote="kelly@192.168.1.53"

**Comment by pedroetb** [comment]
@privatesam hi, I agree with @jezek solution, you should use parameters to set your values.
