### ISSUE TITLE
How to keep only a certain number of log files

### ISSUE THREAD

**Issue by tortoo** [pedroetb/rsync-incremental-backup#19]
The log files in the log folder seem not to be deleted automatically. How to keep only a certain number of log files or  how to disable log files to be copied into log folder?

**Comment by pedroetb** [comment]
It's not implemented yet, but I'm agree with you that it's a needed feature. I'll try to release soon a new version including this.

For the moment, you can delete them manually.

**Comment by tortoo** [comment]
Great thanks! Looking forward to this new feature!
