### ISSUE TITLE
rsync-incremental-backup-local fails if src directory has spaces in name

### ISSUE THREAD

**Issue by sputnik63** [pedroetb/rsync-incremental-backup#2]
If src directory has space in its name, the backup fails giving errors like:
```
rsync: link_stat "/home/user/path" failed: No such file or directory (2)
rsync: link_stat "/home/user/withspace" failed: No such file or directory (2)
```
The solution is to add quotes at line 111 that becomes:
`rsync ${rsyncFlags} "${src}/" "${bak0}/"`
This works for me. I'll check also remote backup asap

**Comment by pedroetb** [comment]
Thanks! Certainly, I haven't tested it with spaces in path. If you want use it without modifying the script, maybe a backslash (\) before spaces can solve the problem.

But using quotes around path variables sounds good to me, I'll check it soon.

**Comment by sputnik63** [comment]
No Pedro, the backslash is useless. It was the first attemp I did

**Comment by jerome-pouiller** [comment]
@pedroetb Indeed, all reference to shell variables have be within double quotes. Thus:

    $ VAR="foo bar"
    $ ls $VAR
    ls: cannot access 'foo': No such file or directory
    ls: cannot access 'bar': No such file or directory
    $ ls "$VAR"
    ls: cannot access 'foo bar': No such file or directory

**Comment by pedroetb** [comment]
@sputnik63 ok, I will quote variable references in next update.
@jerome-pouiller agree, thanks!
