### ISSUE TITLE
Backup fails with rsync warning "some files vanished before they could be transferred"

### ISSUE THREAD

**Issue by Henri-J-Norden** [pedroetb/rsync-incremental-backup#22]
I use the script to back up my root filesystem, but occasionally it errors likely due to some transient/temporary files changing:
```
2021/10/16 06:02:14 [25186] rsync warning: some files vanished before they could be transferred (code 24) at main.c(1183) [sender=3.1.1]

[2021-10-16T06:02:14+03:00] Backup failed, try again later
```

I don't think the backup should be considered to have failed - all non-temporary files were copied after all. Currently, however, the next backup will log the following:
`[2021-10-17T05:30:01+03:00] Last backup failed, backups will not be rotated`

Excluding files that are likely to change (e.g. /tmp/*) helps, but it's doesn't really solve the problem. Files can "randomly" disappear from other directories as well and the race condition is still present - even if it is less likely to happen.

**Comment by pedroetb** [comment]
Ok, seems it's returning code 24, non-zero, so it will be interpreted as an error.

[Here](https://unix.stackexchange.com/questions/86879/suppress-rsync-warning-some-files-vanished-before-they-could-be-transferred) is a possible fix to this, filtering that exit code specifically.

Fixing it soon, thx!
