### ISSUE TITLE
Use bash built-in printf rather than external `date` command

### ISSUE THREAD

**Issue by Megver83** [pedroetb/rsync-incremental-backup#24]
Bash built-ins tend to be faster than external commands and preferred for shell scripts. `date` can be easily replaced with `printf` time format, like this example:

````
$ time date +%Y-%m-%d
2022-05-28
real    0m0,001s
user    0m0,001s
sys     0m0,000s
$ time printf "%(%Y-%m-%d)T"
2022-05-28
real    0m0,000s
user    0m0,000s
sys     0m0,000s
````

It kinda keeps the `date` format. Plus, it can be used to directly set variables with the `-v` option.
Just type `printf --help` for more info :D

**Comment by pedroetb** [comment]
I will take a look into this for next release, thanks!
