### ISSUE TITLE
ssh custom port

### ISSUE THREAD

**Issue by mox63** [pedroetb/rsync-incremental-backup#3]
Hi Pedro,
I'm wonder where I can change in the script the default ssh port.
In my Firewall I set a custom port number to access at NAS server.
Any help is appreciated.
Thank you and "y saluda a tus hermosas islas"
Maurizio

**Comment by pedroetb** [comment]
Hi Maurizio,
you can set it directly on your `remote` variable, like `remote:port`, or you can define it using ssh_config (creating an alias for your user, remote host, port, keys, etc.). You can see more about that on project readme, or directly on this [link](https://www.cyberciti.biz/faq/create-ssh-config-file-on-linux-unix/).

Hope this help you, and "saludos desde el paraíso!".

**Comment by mox63** [comment]
Ok,
changing the variable in remote:port don't take effect, I have the same error.
But ssh alias strategy work! perfect (and I learn something new, thank!).

I have some other issue and error.
rsync: --info=progress2: unknown option
rsync error: syntax or usage error (code 1) at main.c(1453) [client=3.0.9]
[2018-03-23T08:07:03+0100] Backup failed, try again later

I try to indagate
Best
Maurizio

**Comment by mox63** [comment]
Ok,
good news. All works.
Jut to know.
**rsync: --info=progress2: unknown option**
because I have an old server an also old rsync version, I eclude from the script the option

**add custom port** in the remote variable, remote="server:port", does not work.
I solve with ssh_config alias

**At line 21, tempLogPath**="${ownFolderPath}/${remote}_${dst//[\/]/\\}"
the construction of the path truncates some parts and inserts \ instead of /
I normalized this way 
tempLogPath="${ownFolderPath}/${remote}_${dst}"

at last, the script return me an arror because **exclude.txt** doesn't exist,
I create an empty exclude.txt

And...
now it's all OK
Thanks for your really usefull script

Best
Maurizio

**Comment by pedroetb** [comment]
Thanks for your feedback!

About ssh port, I made a mistake with `ssh` command. You can set it with `-e` parameter, redefining the internal ssh command used by rsync (`rsync -e "ssh -p $portNumber" ...`), but I also prefer the ssh_config method. More info [here](http://mike-hostetler.com/blog/2007/12/08/rsync-non-standard-ssh-port/).

If your rsync version at remote host is outdated, you can omit reporting parameters or use other supported by that version, but there is no problem if you omit that.

I will add some checking on the exclude.txt file to avoid errors, thanks!

And about `tempLogPath`, I will try your suggestion on next upgrades.

Thank you again for your thoughts!
