### ISSUE TITLE
rsync remote creates text files instead of symlinks

### ISSUE THREAD

**Issue by proninyaroslav** [pedroetb/rsync-incremental-backup#30]
I use `rsync-incremental-backup-remote` script:

```
rsync "${rsyncShellParams[@]}" -aAhv${compressionFlag} --numeric-ids -M--fake-super --progress --timeout="${timeout}" \
	--delete --no-W --partial-dir="${partialFolderName}" --link-dest="${bak1}/" --log-file="${logFile}" \
	--exclude="${ownFolderName}/" \
	--exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} \
	--exclude-from="${exclusionFilePath}" ${additionalFlags} \
	"${src}/" "${remoteBak0}/"
```

and in the backup I see that instead of symlinks there are text files, inside of which there is a path to the destination file. For example, instead of the `/bin -> /usr/bin` symlink, it creates a `/bin` file with the text content `/usr/bin`.
It worked fine before, about a year ago exactly. But then I didn’t check the backups and something changed.

**Comment by pedroetb** [comment]
Hi, using same command before was working fine? Any change on your script or storage? What version are you using? Destination file is available?

**Comment by proninyaroslav** [comment]
@pedroetb 
I'm using the latest version of the script. I also tried using the old one, but the result is the same. I think the changes happened on the rsync side.

**Comment by proninyaroslav** [comment]
By the way, I have no problems with the script that makes a local system backup, only with a network one.

**Comment by proninyaroslav** [comment]
@pedroetb 
Do you have any thoughts or ideas why this might be? I can give more info.

**Comment by pedroetb** [comment]
Not really, I'm thinking in storage modification/corruption or maybe an undiscovered bug at network backup script.

You have reached backup rotation limits both on local and network backups?

**Comment by proninyaroslav** [comment]
@pedroetb 
I tried deleting old backups and starting over, but that didn't help.

**Comment by pedroetb** [comment]
You deleted the oldest backup? Be careful, when a file is not changed, the oldest one is the current version.

**Comment by proninyaroslav** [comment]
@pedroetb 
I know, but since this is a remote backup, I didn’t risk anything, I tried to create a backup from scratch.

**Comment by pedroetb** [comment]
> I tried to create a backup from scratch

And you detected this problem in this new backup? After how many backup rotations?

**Comment by proninyaroslav** [comment]
@pedroetb 
I just made a remote backup from scratch and the problem is the same. Symlinks are text files (colored green in the screenshot). This problem also appears without rotations, immediately during the first backup.

![2023-10-12 20-05-50](https://github.com/pedroetb/rsync-incremental-backup/assets/7840559/16956b8c-7e90-4c01-8f52-cf4e546611b4)

![image](https://github.com/pedroetb/rsync-incremental-backup/assets/7840559/962ddd4c-40fc-4f59-9de9-d2f9aa6b1262)

```
sent 264,10G bytes  received 27,24M bytes  54,21M bytes/sec
total size is 394,88G  speedup is 1,50

[2023-10-12T20:03:35+0300] Backup completed successfully

[2023-10-12T20:03:35+0300] Sending current log to target
rsync-incremental-backup_2023-10-12_18-42-22. 100%  263MB  88.4MB/s   00:02
```

**Comment by pedroetb** [comment]
I think those are actually symlinks originally at your system. For example, `bin -> usr/bin` (`data/bin` is pointing to `data/usr/bin`). You have seen this with another file (not a directory)?

Here is one of my backups, with the same behaviour:
```sh
... backup/data$ ls -la
total 76
drwxr-xr-x  19 root root 4096 Apr  1  2023 .
drwxrwxrwx   4 root root 4096 Apr  1  2023 ..
drwxr-xr-x   2 root root 4096 Feb 23  2022 .disk
lrwxrwxrwx  13 root root    7 Feb 23  2022 bin -> usr/bin
drwxr-xr-x   4 root root 4096 Nov  4  2022 boot
drwxr-xr-x   2 root root 4096 Mar 31  2023 dev
drwxr-xr-x 115 root root 4096 Dec  1  2022 etc
drwxr-xr-x   4 root root 4096 Mar 22  2022 home
lrwxrwxrwx  13 root root    7 Feb 23  2022 lib -> usr/lib
drwxr-xr-x   2 root root 4096 Apr  8  2022 media
drwxr-xr-x   2 root root 4096 Mar 25  2022 mnt
drwxr-xr-x   3 root root 4096 Mar 23  2022 opt
dr-xr-xr-x   2 root root 4096 Jan  1  1970 proc
drwx------   7 root root 4096 Dec  1  2022 root
drwxr-xr-x   2 root root 4096 Apr  1  2023 run
lrwxrwxrwx  13 root root    8 Feb 23  2022 sbin -> usr/sbin
drwxr-xr-x   6 root root 4096 Feb 23  2022 snap
drwxr-xr-x   2 root root 4096 Feb 23  2022 srv
dr-xr-xr-x   2 root root 4096 Jan  1  1970 sys
drwxrwxrwt   2 root root 4096 Apr  1  2023 tmp
drwxr-xr-x  11 root root 4096 Feb 23  2022 usr
drwxr-xr-x  12 root root 4096 Dec  1  2022 var
```

**Comment by pedroetb** [comment]
You are able to create manually a symlink where your backups are stored? Maybe you are using an incompatible filesystem?

Found this: <https://superuser.com/questions/638998/easiest-way-to-restore-symbolic-links-turned-into-text-files>

It seems that this is a common problem, getting symlinks "converted" to text files.

**Comment by proninyaroslav** [comment]
@pedroetb 
Hmm, early I use `ext4` on my local machine, but now I use `btrfs`. The server used `xfs` all the time. Maybe this is the reason and I didn't notice that the backups began to have broken symlinks. Thank you for the link, I'll try to restore the symlinks. This probably needs to be added to my script so that after each backup it restores the symlinks

**Comment by proninyaroslav** [comment]
The problem is how to automate this. The fact is that there may be other text files in the backup (for example, config files), which it will try to convert into a symlink. This is a difficult task.

**Comment by pedroetb** [comment]
First I would identify which is the problem to be sure. Restoring after each backup doesn't sound good, maybe there is a better option.

**Comment by proninyaroslav** [comment]
@pedroetb 
I tried to make a backup from local `ext4` to server `xfs`, the problem is the same. I also tried `btrfs` -> `btrfs` and `ext4` -> `ext4` and it had no effect. So more likely the problem is not in a file system. In addition, the local version of the script works great. The problem occurs with the remote script.

**Comment by pedroetb** [comment]
It's strange. Both local and remote scripts follow the same logic.

Can you check rsync version at local and remote systems?

**Comment by proninyaroslav** [comment]
3.2.7 on both.

**Comment by jezek** [comment]
Pardon my intrusion. I'm using the remote backup script for more than a year and it handles symlinks correctly for me.

I've tried to ask about this issue a [chatbot](https://poe.com/s/Ggc1FNqHrR7RvVzPKbA5) and it suggested to look, if the user has rights to create symlinks, or check if there is a `rsyncd.conf` with disabled symlinks on the remote machine.

**Comment by pedroetb** [comment]
Thanks for intrusion! @jezek 

I'm thinking that @proninyaroslav issue is not related with backup script itself, but with remote system instead.

**Comment by proninyaroslav** [comment]
@jezek 
I was able to create a symlink under `backup` user (from which I send the backup to the server):
```
$ ssh backup@server
$ [backup@server] ln -s /srv/backup/data/bin /srv/backup/data/test
$ [backup@server] ls -la /srv/backup/data/
lrwxrwxrwx.   1 backup backup    3 Oct 13 17:06 test -> bin
```

My `rsyncd.conf`:
```
uid = root
gid = root
use chroot = false
max connections = 5
pid file = /var/run/rsyncd.pid
exclude = lost+found/
transfer logging = yes
timeout = 900
# ignore nonreadable = yes
dont compress   = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2

[backup]
       path = /srv/backup
       comment = Backup directory
       read only = false
```


@pedroetb 
> but with remote system instead.

I tried to do the same on another PC, using it as rsync server on the local network with the default `rsyncd.conf`. The problem is the same as on my server. I use Fedora on all my PCs. Alternatively, I can install another distro and try again. Maybe this is some kind of bug in the Fedora.

**Comment by jezek** [comment]
@proninyaroslav  Have you tried to  do a simple test with rsync? Something like this?
```bash
jezek@notebook ~ 
$ cd /tmp                                                                                                                                     [22:35:14]
                                                                                                                                              [22:35:14] 
jezek@notebook /tmp 
$ mkdir test-backup                                                                                                                           [22:35:31]
                                                                                                                                              [22:35:31] 
jezek@notebook /tmp 
$ cd test-backup                                                                                                                              [22:35:35]
                                                                                                                                              [22:35:35] 
jezek@notebook /tmp/test-backup 
$ echo test text > file.txt                                                                                                                   [22:35:53]
                                                                                                                                              [22:35:53] 
jezek@notebook /tmp/test-backup 
$ ln -s ./file.txt ./symlink-relative                                                                                                         [22:36:18]
                                                                                                                                              [22:36:18] 
jezek@notebook /tmp/test-backup 
$ ln -s /tmp/test-backup/file.txt ./symlink-absolute                                                                                          [22:36:49]
                                                                                                                                              [22:36:49] 
jezek@notebook /tmp/test-backup 
$ ls -la                                                                                                                                      [22:37:09]
total 4
drwxr-xr-x  2 jezek jezek 100 okt 13 22:36 .
drwxrwxrwt 18 root  root  520 okt 13 22:35 ..
-rw-r--r--  1 jezek jezek  10 okt 13 22:35 file.txt
lrwxrwxrwx  1 jezek jezek  25 okt 13 22:36 symlink-absolute -> /tmp/test-backup/file.txt
lrwxrwxrwx  1 jezek jezek  10 okt 13 22:36 symlink-relative -> ./file.txt
                                                                                                                                              [22:37:09] 
jezek@notebook /tmp/test-backup 
$ rsync -a /tmp/test-backup jezek@192.168.0.2:/tmp                                                                                           [22:37:43]
                                                                                                                                              [22:37:44] 
jezek@notebook /tmp/test-backup 
$ ssh -t jezek@192.168.0.2 exec 'ls -la /tmp/test-backup'                                                                                    [22:39:00]
total 12
drwxr-xr-x 1 jezek jezek   80 Oct 13 22:36 .
drwxrwxrwt 1 root  root  3482 Oct 13 22:37 ..
-rw-r--r-- 1 jezek jezek   10 Oct 13 22:35 file.txt
lrwxrwxrwx 1 jezek jezek   25 Oct 13 22:36 symlink-absolute -> /tmp/test-backup/file.txt
lrwxrwxrwx 1 jezek jezek   10 Oct 13 22:36 symlink-relative -> ./file.txt
Connection to 192.168.0.2 closed.
```

**Comment by proninyaroslav** [comment]
@jezek 
Yes it works, if I use basic `rsync -a ...`:
```
drwxr-xr-x. 3 yaroslav yaroslav 140 Oct 14 10:13 .
drwxr-xr-x. 3 yaroslav yaroslav  60 Oct 14 10:17 ..
drwxr-xr-x. 2 yaroslav yaroslav  40 Oct 14 10:12 dir
-rw-r--r--. 1 yaroslav yaroslav  10 Oct 14 10:12 file.txt
lrwxrwxrwx. 1 yaroslav yaroslav   5 Oct 14 10:12 symlink-dir -> ./dir
lrwxrwxrwx. 1 yaroslav yaroslav  10 Oct 14 10:13 symlink-file -> ./file.txt
-rw-r--r--. 1 yaroslav yaroslav  10 Oct 14 10:12 symlink-file-abs
```

**Comment by jezek** [comment]
Now you know, the basic `rsync` command works, now add parameters one-by-one to get your `rsync` command from [your first post here](https://github.com/pedroetb/rsync-incremental-backup/issues/30#issue-1899813576) and you should figure out what is the matter, what option makes it worse.

Note: I see, that your `symlink-file-abs` is not a link. Maybe `rsync` has problem with links that point to non-existent file (because backup has different prefix directories) and changes them into file.

**Comment by proninyaroslav** [comment]
> Note: I see, that your `symlink-file-abs` is not a link

It seems that bash didn't display this as a symlink. This happened in both cases (on local and remote machine)

**Comment by jezek** [comment]
> It seems that bash didn't display this as a symlink. This happened in both cases (on local and remote machine)

Are you sure it is just a bash fault and it didn't display it as link? Check the dir with `file *` command.

On my test dir it looks like this
```bash
jezek@notebook /tmp/test-backup 
$ ls -li                                                                                                                                      [16:47:07]
total 8
7615 -rw-r--r-- 2 jezek jezek 15 okt 14 16:44 file.txt
7615 -rw-r--r-- 2 jezek jezek 15 okt 14 16:44 hardlink.file.txt
7617 lrwxrwxrwx 1 jezek jezek 25 okt 13 22:36 symlink-absolute -> /tmp/test-backup/file.txt
7616 lrwxrwxrwx 1 jezek jezek 10 okt 13 22:36 symlink-relative -> ./file.txt
                                                                                                                                              [16:47:07] 
jezek@notebook /tmp/test-backup 
$ file *                                                                                                                                      [16:47:10]
file.txt:          ASCII text
hardlink.file.txt: ASCII text
symlink-absolute:  symbolic link to /tmp/test-backup/file.txt
symlink-relative:  symbolic link to ./file.txt
                                                                                                                                              [16:47:10] 

```

Note: I added a hardlink to the file list using `ln file.txt hardlink.file.txt` (you can see the same node-id).

**Comment by proninyaroslav** [comment]
@jezek 
```
826 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 file.txt
825 lrwxrwxrwx. 1 yaroslav yaroslav 8 Oct 14 18:08 symlink.txt -> file.txt
827 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 symlink_abs.txt
```

```
backup/file.txt:        ASCII text
backup/symlink_abs.txt: ASCII text
backup/symlink.txt:     symbolic link to file.txt
```

**Comment by jezek** [comment]
@proninyaroslav 
> backup/symlink_abs.txt: ASCII text

On your backup, it is not a symlink, just a file (even not a hardlink). Is this the computer you backup from, or the one you backup to?

**Comment by proninyaroslav** [comment]
@jezek 

> Is this the computer you backup from, or the one you backup to?

It's different machines.

P.S: I tried running a command that does exactly the same thing as the command from the script:

`rsync -aAhv --numeric-ids -M--fake-super --progress --delete --no-W backup/ yaroslav@server:/tmp/backup`

and I got this error:

```
rsync: [generator] failed to write xattr user.rsync.%stat for "/tmp/backup/symlink.txt": Operation not supported (95)
./
file.txt
              5 100%    0,00kB/s    0:00:00 (xfr#1, to-chk=2/4)
symlink.txt -> file.txt
symlink_abs.txt
              5 100%    4,88kB/s    0:00:00 (xfr#2, to-chk=0/4)
```

and `symlink.txt` became a text file with the path to the file, the same problem that I initially encountered:

```
844 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 file.txt
843 -rwxrwxrwx. 1 yaroslav yaroslav 8 Oct 14 18:08 symlink.txt
845 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 symlink_abs.txt
```

Apparently I didn't see these errors during the system backup. The question is why the operation is not allowed, although I used to make backups and didn't experience any problems, it's difficult to say when this happened.

**Comment by proninyaroslav** [comment]
P.P.S: Removing `-M--fake-super` from the command solves the problem:

```
858 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 file.txt
857 lrwxrwxrwx. 1 yaroslav yaroslav 8 Oct 14 18:08 symlink.txt -> file.txt
859 -rw-r--r--. 1 yaroslav yaroslav 5 Oct 14 18:08 symlink_abs.txt
```

**Comment by jezek** [comment]
@proninyaroslav 
> The question is why the operation is not allowed, although I used to make backups and didn't experience any problem

I don't know, why it isn't allowed. Maybe some permissions problem. I hope you figure it out.

**Comment by proninyaroslav** [comment]
@jezek 
From what I could find, to use `-M--fake-super` command you need to mount FS with the `user_xattr` flag on the server side.  I'll try this and post the results.

**Comment by proninyaroslav** [comment]
So, xfs supports xattrs by default, so that's not the problem. It's not clear why rsync can't do this. I just did this using `setfattrs` manually and it works on xfs

**Comment by proninyaroslav** [comment]
@jezek 
The problem with xattrs seemed to only be in `/tmp`. Now I tried to copy this directly to the backup directory. There was no error. But the symlink still became a text file. So, the problem in `-M--fake-super`. Maybe this is standard `fake-super` behavior now? Could you check this on your computer?

**Comment by jezek** [comment]
@proninyaroslav 
> Could you check this on your computer?

```bash
jezek@notebook /tmp/test-backup 
$ ls -li; file *                                                                                                                              [18:39:05]
total 8
7615 -rw-r--r-- 2 jezek jezek 15 okt 14 16:44 file.txt
7615 -rw-r--r-- 2 jezek jezek 15 okt 14 16:44 hardlink.file.txt
7617 lrwxrwxrwx 1 jezek jezek 25 okt 13 22:36 symlink-absolute -> /tmp/test-backup/file.txt
7616 lrwxrwxrwx 1 jezek jezek 10 okt 13 22:36 symlink-relative -> ./file.txt
file.txt:          ASCII text
hardlink.file.txt: ASCII text
symlink-absolute:  symbolic link to /tmp/test-backup/file.txt
symlink-relative:  symbolic link to ./file.txt
                                                                                                                                              [18:39:05] 
jezek@notebook /tmp/test-backup 
$ ssh -t jezek@192.168.0.2 exec 'ls -li /tmp/test-backup'                                                                                    [18:39:17]
ls: cannot access '/tmp/test-backup': No such file or directory
Connection to 192.168.0.2 closed.
2 ↵                                                                                                                                           [18:39:18] 
jezek@notebook /tmp/test-backup 
$ rsync -a -M--fake-super /tmp/test-backup jezek@192.168.0.2:/tmp                                                                            [18:39:27]
                                                                                                                                              [18:39:28] 
jezek@notebook /tmp/test-backup 
$ ssh -t jezek@192.168.0.2 exec 'ls -li /tmp/test-backup'                                                                                    [18:39:32]
total 16
8505756 -rw-r--r-- 1 jezek jezek 15 Oct 14 16:44 file.txt
8505757 -rw-r--r-- 1 jezek jezek 15 Oct 14 16:44 hardlink.file.txt
8505754 -rwxrwxrwx 1 jezek jezek 25 Oct 13 22:36 symlink-absolute
8505755 -rwxrwxrwx 1 jezek jezek 10 Oct 13 22:36 symlink-relative
Connection to 192.168.0.2 closed.
                                                                                                                                              [18:39:33] 
jezek@notebook /tmp/test-backup 
$ ssh -t jezek@192.168.0.2 exec 'file /tmp/test-backup/*'                                                                                    [18:39:44]
/tmp/test-backup/file.txt:          ASCII text
/tmp/test-backup/hardlink.file.txt: ASCII text
/tmp/test-backup/symlink-absolute:  ASCII text, with no line terminators
/tmp/test-backup/symlink-relative:  ASCII text, with no line terminators
Connection to 192.168.0.2 closed.
                                                                                                                                              [18:39:44] 
```

**Comment by jezek** [comment]
@proninyaroslav I see, why I'm not affected by this, when I do backup. The `-M--fake-super` is only in `rsync-incremental-backup-system-remote` and I'm using only `rsync-incremental-backup-remote`.

**Comment by proninyaroslav** [comment]
@jezek 
Yes, apparently it was a false alarm 😃 Maybe I didn't notice this before. It’s just that this time I forgot that it is necessary to specify `-M--fake-super` when **restoring** a backup, then the symlinks from text files turn into real symlinks on the local machine.

**Comment by pedroetb** [comment]
Wow, nice support @jezek thanks! Glad to see that your backups are alright @proninyaroslav
