### ISSUE TITLE
CHOWN failed: Operation does not permitted

### ISSUE THREAD

**Issue by achmet9948** [pedroetb/rsync-incremental-backup#6]
Hello,
I have a Synlogy NAS and a mount on the linux server. 

Now I have follwing problem: 
I tried to backup my MailBoxes. By copy the files the Shell write down the error: CHOWN /path/to/file failed: Operation not permitted. 
Can someone help me to fix this error? 
Are the Settings on the Synology wrong?

**Comment by pedroetb** [comment]
Hi, can you provide the real filename which is causing trouble?

Maybe is just a file which you are forbidden to access with that user. You can exclude it if you don't need to backup that file.

**Comment by achmet9948** [comment]
Hello, 
I found my issue and now it works.
