### ISSUE TITLE
Backup folder timestamp

### ISSUE THREAD

**Issue by pnkhanh** [pedroetb/rsync-incremental-backup#8]
Hello, I tried the scripts and it worked well.
But the timestamps of the backup folder are not correct.
They did not change overtime.

[/share/Backup/share/backup] # ls -al
total 20
drwxr-xr-x  5 admin administrators 4096 2018-06-29 15:45 ./
drwxr-xr-x  4 admin administrators 4096 2018-06-29 15:45 ../
drwxrwxrwx 44 admin administrators 4096 2018-06-29 11:53 backup.1/
drwxrwxrwx 44 admin administrators 4096 2018-06-29 11:53 backup.2/
drwxr-xr-x  2 admin administrators 4096 2018-06-29 15:17 log/

**Comment by pedroetb** [comment]
Hi, I will check that, thanks!

I have a possible TODO to name the backup folders with the timestamp when they were created, maybe this can be a better option to check the moment of backup quickly.

The backup rotation works renaming the backup folders (1 to 2, 2 to 3, etc), and this can be a side effect of that. This way of checking the date of backup may be interesting too, I will try to reflect the modification time in folder attributes.

In the meantime, you can check dates in backup log files (name and attributes).

Thanks!

**Comment by JamesRWP** [comment]
@pedroetb 
I have the same problem, if there are subfolders in the backup folder and the data is in the subfolder, the data changes, however the folder date does not change.

I added a custom command to fix the bug.

#If the backup is successful, update the backup folder time
if [ $rsyncFail -eq 0 ]; then
    touchTime="$(${dateCmd} +%Y%m%d)$(${dateCmd} +%H%M.%S)"
    ssh "${sshParams[@]}" "${remote}" "touch -m -t $touchTime ${bak0}"
fi

**Comment by pedroetb** [comment]
Hi @JamesRWP, thanks for sharing.

After checking all my backups I detected the problem in some of them too. I'm not sure why affects only some of them, but the problem is there.

I like your fix command, will include in scripts on next update. Thank you!
