### ISSUE TITLE
[New feature] Add support for rsync_password

### ISSUE THREAD

**Issue by clementduveau** [pedroetb/rsync-incremental-backup#9]
Hi !

I intended to use this scripts to backup one of my server on a managed service like AWS Glacier.

Unfortunately, ssh keys are not supported right now, a password is generated by the provider.

I explored the code and it is quit complex for me to refactor it properly. I do not master it for the moment.

For now, I am using a simple rsync script. But I think it could be useful to implement it in order to make this script popular on OVH.

Have a nice day

**Comment by pedroetb** [comment]
Hi Clement,

I think you can define the password to use by prepending ` sshpass -p 'password' ` to all `ssh` commands (see https://unix.stackexchange.com/questions/38737/ssh-login-with-clear-text-password-as-a-parameter).

If this becomes a highly demanded feature, I can try to detect if user is using public/private keys or password, to add it dynamically.

Thanks!

**Comment by clementduveau** [comment]
Hi Pedro,

I just give it a try. It doesn't work. Here what I think could be the issues:

1. OVH's Glacier accept rsync, not plain SSH. So rsync-incremental-backup is rejected when checking remote connection.
2. Then, I'm not sure that sshpass will correctly give the password for each connection.

I think about forking your repo and build a script adapted for OVH's Glacier.

**Comment by pedroetb** [comment]
I'm not familiarized with Glacier, but after a short review I think you have to adapt your connection and data to Glacier format (saw they have a CLI, maybe it is enough for that task). I didn't saw anything about a specific rsync connection with Glacier, I'm not sure what are you refering at.

Any fork is welcome, so if you can handle that feature it would be great.

Thanks!

**Comment by clementduveau** [comment]
Hi,

I worked on the problem. Actually the limitations on OVH's Glacier make it quite difficult to adapt the script.

1. Authentication

You can use rsync with the OVH's archive system but you can't use SSH keys. The system is based on APIs, rsync is more like a convenient way to use them than a complete integration.

2. File transfer limitations

I finally used Duplicati to backup my data to the cold archive, and even with a such advanced software I had to change some parameters like splitting huge files into 256MiB files and never try to read a file to check if remote data and local data are sync (you have to wait several minutes/hours to read one file) making the system totally stateful...


In my opinion, the cold storage archives are not designed to be used with a complex rsync script, but only simple use cases.
I think this is irreleveant to try to integrate rsync_password to this script. The time to develop the feature will be too high comparing to the benefits.

I close this issue.

**Comment by pedroetb** [comment]
Ok, thanks for sharing your conclusions!
